<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSx4n00m\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSx4n00m/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSx4n00m.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSx4n00m\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSx4n00m\appProdProjectContainer([
    'container.build_hash' => 'Sx4n00m',
    'container.build_id' => '0de5a45c',
    'container.build_time' => 1646946137,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSx4n00m');
