<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIjmrsgn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIjmrsgn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIjmrsgn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIjmrsgn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIjmrsgn\appDevDebugProjectContainer([
    'container.build_hash' => 'Ijmrsgn',
    'container.build_id' => '784299ed',
    'container.build_time' => 1646947071,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIjmrsgn');
